export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_CLIENTS = 'GET_ALL_CLEINTS';
export const GET_ALL_SUPPLIERS = 'GET_ALL_SUPPLIERS';
export const GET_ALL_SHIPPING = 'GET_ALL_SHIPPING';
export const GET_ALL_ACCOUNTS = 'GET_ALL_ACCOUNTS';
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
export const GET_ALL_USERS = 'GET_ALL_USERS';
