const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
const GET_ALL_CLIENTS = 'GET_ALL_CLEINTS';
const GET_ALL_SUPPLIERS = 'GET_ALL_SUPPLIERS';
const GET_ALL_SHIPPING = 'GET_ALL_SHIPPING';
const GET_ALL_ACCOUNTS = 'GET_ALL_ACCOUNTS';
const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
const GET_ALL_USERS = 'GET_ALL_USERS';
const CHANEGE_PRODUCT_MODAL = 'CHANGE_PRODUCT_MODAL';


export {
    GET_ALL_PRODUCTS,
    GET_ALL_CLIENTS,
    GET_ALL_SUPPLIERS,
    GET_ALL_SHIPPING,
    GET_ALL_ORDERS,
    GET_ALL_ACCOUNTS,
    GET_ALL_USERS,
    CHANEGE_PRODUCT_MODAL
};